//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imdb_t2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string first_Name { get; set; }
        public string secondName { get; set; }
        public string e_mail { get; set; }
        public string password { get; set; }
        public byte[] image { get; set; }
        public bool isAdmin { get; set; }
    }
}
