//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imdb_t2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public int IdDirector { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public int age { get; set; }
        public byte[] image { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
