//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imdb_t2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public int totalRate { get; set; }
        public byte[] image { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public int decription { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Actor Actor1 { get; set; }
        public virtual Director Director { get; set; }
    }
}
